### ISSUE TITLE
Issues with implementing variable heat capacity calculation with bucket depth

### ISSUE THREAD

**Issue by mcthreems** [ExeClim/Isca#101]
I have attempted to make a small change in the heat capacity calculation within the mixed layer module. The change simply adjusts the calculation to use the actual bucket depth if it is lower than the specified mixed-layer depth, with the land value used as a minimum value. However, when I attempt to run the model with this edit, it crashes immediately due to bad temperatures. Trying to investigate the issue has given me little insight into what might be wrong. I am attaching here the edited mixed layer file, with my edits marked with "!MMM" and located on line 524.
[mixed_layer.txt](https://github.com/ExeClim/Isca/files/4073775/mixed_layer.txt)

**Comment by sit23** [comment]
@mcthreems - A quick clarification first - I'm a little confused as to what circumstance this will apply. Presumably we're thinking of Titan lakes, so that if the bucket depth is locally shallower than the prescribed mld then we adopt a lower value, with the lowest possible value being the land mld? My Earth perspective was confused at first, because over Earth's oceans you're imagining an essentially infinite bucket depth, so there's never any way it would dry out over ocean.

In terms of why this is happening, have you tried setting the land mld instead of the bucket depth as a first try? Does that still give you bad temperatures? That will hopefully tell you that it's that part of your code that is causing the problems.

Another quick one to check would be to try outputting the mld straight after this calculation, before any temperature changes are done. Would be good to check that the mld is a reasonable number (is it perhaps a strangely large number by accident?)

In terms of other possibilities, the model does tend to get a little upset when there are large contrasts in mld as this means large contrasts in temperatures -> high winds -> CFL errors. Might be worth trying lots of smaller timesteps to see if this is possibly the issue. 

I guess you might have tried some of these things already. Hopefully there's something there that'll be useful.

**Comment by sit23** [comment]
Also, is it failing on the first timestep, or is it failing after a few? I can imagine this kind of setup leading to a feedback loop of very rapid bucket emptying and evaporation if it's running in a dry atmosphere for a few timesteps.

**Comment by sit23** [comment]
Have you tried initialising with a really deep and full bucket? That might help it run for a few timesteps where you know this condition won't be satisfied.

**Comment by mcthreems** [comment]
Regarding your first question, we are running simulations with a pseudo-aquaplanet version of Earth in which we vary the initial bucket depth. The pseudo is because we have the model treat all grid cells as land cells, even though we can have up to 1000m of water in them. The way the model currently handles this is just applying the land prefactor for every cell. We wanted to avoid that land prefactor until a cell is either dry or would have a calculated heat capacity lower than the dry value, hence the system I described.

**Comment by mcthreems** [comment]
After trying some of your suggestions, I finally realized the issue was a simple mistake on my part. When I was implementing the "where" functions with the bucket depth array, I assumed the dimensions would match the order of the output dimensions. As it turns out, they are reversed from the output dimensions, and thus the time dimension is the 3rd rather than the 1st. Once I switched the "size" function to the 3rd dimension, the model ran fine (up until later issues with crashing due to what looks like cold temperatures).

**Comment by mcthreems** [comment]
Regarding those later issues, I'll paste in the error message here just for reference. If this constitutes a separate issues post we can close this one and I'll repost these on a new one.

2020-01-16 23:06:25,950 - isca - DEBUG - PE, location, Textr(curr,future):   3:  43  1  4   100.326    99.942
2020-01-16 23:06:25,950 - isca - DEBUG - PE, location, Uextr(curr,future):   3:  43  1  4  -151.763  -152.305
2020-01-16 23:06:25,951 - isca - DEBUG -
2020-01-16 23:06:25,951 - isca - DEBUG - FATAL from PE    3: spectral_dynamics: temperatures out of valid range

**Comment by mcthreems** [comment]
We figured out that the heat capacity calculation we were editing is in the init function, meaning it isn't done each time step. We've changed it to be located in the function proper such that it is done each time step. I'll close this for now.
