### ISSUE TITLE
Topography to be done in geopotential or true height?

### ISSUE THREAD

**Issue by natgeo-wong** [ExeClim/Isca#206]
Hi!  I've had a look at the given `era_land_t42.nc` file, and I've noticed that zsurf seems to be given in true vertical height rather than geopotential (multiplied by g) height.  Which does Isca use?  There's no mention in current or even the pull-request docs.

**Comment by sit23** [comment]
Hi @natgeo-wong, 

All the topography files we include in the repo will work by default, so indeed Isca does expect the input file to be in true height, rather than geopotential. If you look in the code where it reads the topography, it's reading the height and then multiplying it by g afterwards:
https://github.com/ExeClim/Isca/blob/2b603fa41647671582eb93190a78e73300c41831/src/atmos_spectral/init/spectral_init_cond.F90#L228 

I'd also recommend making sure you output `zsurf` in your output files. Firstly to reassure yourself that the topography is working correctly, and secondly because you'll need it when interpolating your output data onto pressure levels from `sigma` coordinates.

Hope this helps,
Stephen

**Comment by RuthG** [comment]
Just to add 
1. Thanks, we'll add this to the docs. The hope is that in the longer term these will help users find answers to questions like this, but right now it's very much in development.  The docs are currently being written in once monthly team 'docs days' as we are all full time researchers and no one is allocated specifically to model development/maintenance. This means it will take a little while longer til things are settled - sorry for the gaps in the current form. 

2. On the topic of topography, we're aware of Gibbs ripples issues around steep topography that the model's current regularisation doesn't quite fix. Our colleague Greg Colyer (now Oxford) has developed an input smoothing method to help with these. Unfortunately this again is under development due to some issues with updates to the python library used that mean new installs no longer runs stably, on our machines at least. I'm aiming to look at this on 'docs day' next Wednesday and to get this updated and in a pull request ASAP. But if you run into significant Gibbs ripples issues in the mean time get in touch, I should be able to produce a smoothed file from an old conda enviornment.

**Comment by gkvallis** [comment]
And, just to add a bit more, we are always looking for helpers for doc-writing...

**Comment by natgeo-wong** [comment]
Thank you all so much for the quick response!  I wouldnt mind contributing to doc writing once my semester is over (my Quals are in late May).

I have another question regarding topography regularization:

I am currently running some idealized landmass bands spanning entire latitude bands.  However, I am running into `regularize: Failure to converge`, even for settings where there is no topography at all.  I suppose I could just switch off the topography option by preventing reading of the zsurf data file, but there are other experiments where I need the topography where this error occurs as well.

The topography that I created is of gaussian form, and like the landmasses, span latitudinal bands as well.  What should I do in order to achieve convergence, should I increase the number of iterations?

**Comment by RuthG** [comment]
You could either increase the number of iterations, or (assuming I am remembering correctly, it's been a while sorry) you could decrease the value of `ocean_topog_smoothing` in `spectral_dynamics_nml`.

**Comment by natgeo-wong** [comment]
I resolved this issue: orography over land cannot be zero or it will run into convergence issues when zsurf data is turned on.  Need to include some small orography (I used a 50m gaussian curve peaking in the middle of the latitude band)

**Comment by RuthG** [comment]
Ah I'd not understood you had 0 height orography - the usual solution here would be to turn on land, but not orography with the switches in the namelists. This allows 0 height orography and land with altered albedo, roughness, moisture availability & mixed layer depth, without calling the topographic smoothing. Or am I still misunderstanding, do you mean cannot be 0 at any location? If so that's useful to know and should certainly be checked out. Good luck with your quals!

**Comment by natgeo-wong** [comment]
There were some land points where I did not want to include noticeable topography, so I initially just left those points as zero height.  But the models kept crashing for some reason.  So I had to add in topographic height for all land points.

I could not switch off orography because there were other regions where I wanted mountains (basically I was running experiments to see what the effects would be if a certain place had mountains or not).
