### ISSUE TITLE
Equinox_day inconsistency

### ISSUE THREAD

**Issue by ntlewis** [ExeClim/Isca#66]
`equinox_day` (the fraction of the year at which autumn equinox occurs) is set as default to `0.0` in `two_stream_gray_nml` but `0.75` in `rrtm_radiation_nml` and `socrates_nml`. 

Should the value in `two_stream_gray_nml` be set to the correct value of `0.75`?

**Comment by sit23** [comment]
That was done because most people using the grey-radiation code at the time we added it weren't using the Earth calendar, so having equinox as day number 1 was useful. Whereas the typical RRTM user was using the Earth calendar, for which 0.75 is appropriate. We could change the grey-rad one though, given that more people are using that for Earth now.
